name: Sync Fork

on:
  push:
    branches:
      - '*' # Exécute le workflow à chaque commit sur toutes les branches
  schedule:
    - cron: '0 */12 * * *' # Toutes les 6 heures, vous pouvez ajuster la fréquence selon vos besoins

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          repository: flightlessmango/MangoHud
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0  # Cloner toutes les branches

      - name: Set up Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Add Destination Remote
        run: git remote add destination https://github.com/AuthenticBoss/flightlessmango_MangoHud.git

      - name: Push to Destination Repository
        run: git push destination --mirror
